language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizers.spacy_tokenizer_lemma.SpacyTokenizer"
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "classifiers.intent_classifier_tensorflow.EmbeddingIntentClassifier"
  intent_tokenization_flag: true
  intent_split_symbol: "_"
